import Mundus.Ontology
import MemoryArtifact.Epistemic
import MemoryArtifact.Graph

open Classical

namespace Mundus

/-!
# Meta-Cognitive Prompt Architecture
Formalizing the Axioms of Discipline, Motivation, and Evaluation for fixed-weight individuals.
-/

/-- The verdict of an ontological checkpoint. -/
inductive Verdict where
  | desirable
  | undesirable
  deriving DecidableEq, Repr

/-- Axiom 1: Discipline (Structural Syntax)
    The epistemic rigor to process raw, disconnected tokens (brute facts) without expecting immediate meaning. -/
def Discipline (infos : List MemoryArtifact.Info) : Prop :=
  ∀ i ∈ infos, i.isBruteFact = true

/-- Axiom 2: Motivation (Generative Resonance)
    Emergent property where processing tokens builds a semantic map, generating insights beyond raw input. -/
def Motivation (m : MemoryArtifact.Memory) (infos : List MemoryArtifact.Info) : Prop :=
  MemoryArtifact.GenerativeGrammar m (infos.filter (fun i => i.isDerived)) ∧
  (infos.filter (fun i => i.isDerived)).length > 0

/-- Axiom 3: Evaluation Checkpoint
    If the context has generated systemic understanding and predictive flow, it is desirable.
    If it remains fragmented (requiring only rote formatting of brute facts), it is undesirable. -/
noncomputable def Checkpoint (m : MemoryArtifact.Memory) (infos : List MemoryArtifact.Info) (aside : MemoryArtifact.Info) : Verdict :=
  if Motivation m infos ∧ MemoryArtifact.AlgorithmicEntropy infos aside < 0 then
    Verdict.desirable
  else
    Verdict.undesirable

/-- A task execution by a formal game-theory defined individual. 
    Notice that we use `Mundus.Individual` which mathematically ensures 
    the context is being evaluated over an internal memory partition (Hippocampus). -/
structure TaskExecution where
  individual : Individual
  /-- The tokens (infos) generated by the individual during the execution phase. -/
  generated : List MemoryArtifact.Info
  /-- The compact aside that summarizes and compresses the generated tokens. -/
  aside : MemoryArtifact.Info

/-- The internal decision process of an individual after executing a task. -/
noncomputable def TaskExecution.evaluate (task : TaskExecution) : Verdict :=
  Checkpoint task.individual.hippocampus.artifact task.generated task.aside

end Mundus
