name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout mundus
        uses: actions/checkout@v5
        with:
          path: mundus

      - name: Checkout memory-artifact
        uses: actions/checkout@v5
        with:
          repository: CMZN-Consulting/memory-artifact
          path: memory-artifact

      - name: Setup Elan
        run: |
          curl -O --location https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh
          sh elan-init.sh -y --default-toolchain none
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: Build mundus
        run: |
          cd mundus
          lake build
