name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout mundus
        uses: actions/checkout@v5

      - name: Checkout memory-artifact
        uses: actions/checkout@v5
        with:
          repository: CMZN-Consulting/memory-artifact
          path: ../memory-artifact

      - name: Build mundus
        uses: leanprover/lean-action@v1
